### ISSUE TITLE
Json 2Struct bug

### ISSUE THREAD

**Issue by Baelroak** [DAN-AND-DNA/UE_EasyStruct2Json#2]
Hello, before the update yesterday/today everything was working correctly besides me needing a bool for the omit which is great thanks for that, but now for some reason the struct2json seems to be working correctly but when I do Json2Struct it is leaving out some variables, for example In the image below it is setting Player Name back into the struct but it is leaving Character Name empty, Player Name is the first string variable in the struct and Character Name is the last string variable in the struct.

This wasn't happening before the update, also same result if the bool for pretty and omit empty are enabled/disabled

![image](https://user-images.githubusercontent.com/68571188/169629720-cb45fa93-1cc8-46c6-b061-a6323b506744.png)

**Comment by DAN-AND-DNA** [comment]
@Baelroak  Got it，I'll go check it right away

**Comment by DAN-AND-DNA** [comment]
@Baelroak Hi，You can use the Return Value to determine whether the conversion to json was successful
![image](https://user-images.githubusercontent.com/28588158/169634698-2b3a126a-42c2-460a-a4b4-3e4d49f30c85.png)

**Comment by DAN-AND-DNA** [comment]
@Baelroak Since json doesn't support many types, like enum values, is it available to provide logs like:
![image](https://user-images.githubusercontent.com/28588158/169634778-bbf169f4-d2f7-4fed-af38-197ef1699331.png)

**Comment by Baelroak** [comment]
![image](https://user-images.githubusercontent.com/68571188/169638270-a5674027-d1b2-44ac-88f8-9debeb6a31d2.png)

**Comment by Baelroak** [comment]
So notetype is a enum value, how can I work around this?

**Comment by DAN-AND-DNA** [comment]
@Baelroak  The standard json does not support enumerations. I recommended you to use dictionary values instead of enumerations:
```c++
map {"Key:"Value"}
LogBlueprintUserMessages: [BP_TestStruct2Json_Simple_2] {"PlayerName":"Dan","CharacterName":{"0":"A","1":"B","2":"C"}}
```
![image](https://user-images.githubusercontent.com/28588158/169639473-6340baf6-3162-4b16-b608-4d6223c47f47.png)

**Comment by DAN-AND-DNA** [comment]
bug fix: https://github.com/DAN-AND-DNA/UE_EasyStruct2Json/issues/4#issuecomment-1246941628
