### ISSUE TITLE
Enum Problems

### ISSUE THREAD

**Issue by brexGmbH** [DAN-AND-DNA/UE_EasyStruct2Json#4]
Hi,

the plugin seems to be very cool, but it has a problem with Enums.

If I have a valid struct that contains an enum then use the "Struct 2 Json" node and after that the "Json 2 Struct" node it fails.
This is because the "Struct 2 Json" node outputs the enum as a string value (I like that), while the "Json 2 Struct" node cannot convert a string value to the matching enum. "Json 2 Struct" expects an integer instead.

Can you fix that, so that the Json 2 Struct can read string values and select the corresponding enum value?

**Comment by DAN-AND-DNA** [comment]
@brexGmbH Hi, since there is no enumeration data type in the json specification, consider using a dictionary or map instead.
example: https://github.com/DAN-AND-DNA/UE_EasyStruct2Json/issues/2#issuecomment-1133548970

**Comment by brexGmbH** [comment]
@DAN-AND-DNA 
The problem is not that there is no enumeration in json specification, this can be done with strings.

The problem is a bug that makes it unable to read the string and select the corresponding option in the enum.
I just had a look at the code, you actually have implemented string conversion to Enum, but it does not work properly.

I tested it in 4.27. If I provide the following json string:
{"MyEnum": "NewEnumerator2"}
it will correctly select the 3rd option based on the string.

The problem is that if you rename an enum value to something different in the editor, it will still only listen to "NewEnumerator2", even when the editor is restarted.

So the problem is not json, the problem is that 
Enum->GetValueByName(FName(*StrValue));
does not work porperly.

**Comment by DAN-AND-DNA** [comment]
@brexGmbH  Thanks for the feedback, I'm going to fix it now, please wait a moment

**Comment by DAN-AND-DNA** [comment]
@brexGmbH 
You're right, I will do more testing and will update tomorrow or the next day if there is nothing wrong
![image](https://user-images.githubusercontent.com/28588158/190193959-f04ba46c-5a0a-4d5d-83c3-fdfcaaff5bd6.png)
![image](https://user-images.githubusercontent.com/28588158/190197239-be993861-c643-4f30-ad44-bc96eae0baed.png)

**Comment by brexGmbH** [comment]
@DAN-AND-DNA 
Awesome!
Thanks for the super quick response!

**Comment by brexGmbH** [comment]
@DAN-AND-DNA 
It's live now, I tested it and it worked, but it is case sensitive. Not sure if this is inteded behavior. I just made it case insesitive myself now.

**Comment by DAN-AND-DNA** [comment]
@brexGmbH Hi, thanks for the feedback, I can make it case insensitive in the next version, but when the epic review is done, I guess it will be tomorrow or the next day.
