### ISSUE TITLE
Will this work even if the user defined struct has a Map datatype?

### ISSUE THREAD

**Issue by jamesarrojo** [DAN-AND-DNA/UE_EasyStruct2Json#6]
for example if struct is like this:

![image](https://user-images.githubusercontent.com/100826031/215693830-d3b8c778-9877-44dc-80d0-85f4ed14c790.png)

**Comment by jamesarrojo** [comment]
for example if struct is like this:

![image](https://user-images.githubusercontent.com/100826031/215693830-d3b8c778-9877-44dc-80d0-85f4ed14c790.png)

**Comment by jamesarrojo** [comment]
I just purchased the plugin after posting this but the Maps and the nested structs after converting the json string to struct and then back to json were empty. Why is that?

**Comment by DAN-AND-DNA** [comment]
@jamesarrojo I'll check it out later, It may be caused by the recent Unreal version update

**Comment by jamesarrojo** [comment]
> @jamesarrojo I'll check it out later, It may be caused by the recent Unreal version update

okay I will wait for that, thank you

**Comment by DAN-AND-DNA** [comment]
![image](https://user-images.githubusercontent.com/28588158/215803377-91c67f8f-e7ae-45d3-98f2-62e8f445d4f6.png)
![image](https://user-images.githubusercontent.com/28588158/215803563-886b8f05-3187-4440-96ed-f289024c026a.png)

**Comment by DAN-AND-DNA** [comment]
@jamesarrojo  UE 4.27 seems to be no problem

**Comment by jamesarrojo** [comment]
@DAN-AND-DNA we are using UE 4.27.2, will it matter?

**Comment by jamesarrojo** [comment]
this is the JSON string I'm testing it with https://pastebin.com/jA8W9fB7, and this is the struct in unreal engine:
![image](https://user-images.githubusercontent.com/100826031/215807076-2d08f213-2947-465c-b1b7-a1cfa7258a0e.png)


as you can see, nested in that struct are 2 structs and map of floats and a map of integers

this is the print string:
![image](https://user-images.githubusercontent.com/100826031/215808838-7f9b6581-053f-4127-ad17-c8ddb55584ab.png)

**Comment by DAN-AND-DNA** [comment]
![image](https://user-images.githubusercontent.com/28588158/215809164-8d51d6cc-9cba-4c79-8620-ce64c92018a5.png)
![image](https://user-images.githubusercontent.com/28588158/215809258-ec40004d-5e1d-48d7-915c-dce402875931.png)
![image](https://user-images.githubusercontent.com/28588158/215809371-53b7e2ae-d00b-43a3-a514-70d955ccf376.png)

**Comment by DAN-AND-DNA** [comment]
@jamesarrojo You're right, there seems to be a small problem that requires changing the variable name, as shown above

**Comment by DAN-AND-DNA** [comment]
I will fix it in the next few days

**Comment by jamesarrojo** [comment]
ah so in my case, if I change the "Basebody" to something else it will now work?
edit: I think I misunderstood what you meant above
![image](https://user-images.githubusercontent.com/100826031/215811112-62f6b884-5d62-4153-a041-bd2e8636a778.png)

**Comment by jamesarrojo** [comment]
> I will fix it in the next few days

thanks, I will wait for that

**Comment by DAN-AND-DNA** [comment]
![image](https://user-images.githubusercontent.com/28588158/215813859-20a6f79a-72f7-44ac-b3ea-041d3f454f1f.png)

**Comment by DAN-AND-DNA** [comment]
@jamesarrojo The second way of naming variables will fail to resolve, please use the first way of naming variables for the time being

**Comment by jamesarrojo** [comment]
@DAN-AND-DNA I resolved the issue by removing the spaces in the Json string itself, e.g. "Morph Targets" -> "MorphTargets" I left the struct variable name as is
