### ISSUE TITLE
Doesn't work on Linux Server

### ISSUE THREAD

**Issue by wheresthebeefy** [DAN-AND-DNA/UE_EasyStruct2Json#8]
Hello!

It works perfectly when running on a Windows dedicated server, but as soon as I cross-compile to a Linux dedicated server, struct 2 json returns a blank string with the same blueprint (calling the method struct 2 json that takes a struct and outputs json).  UE version 5.1.1.

**Comment by DAN-AND-DNA** [comment]
@wheresthebeefy Okay, I'll fix it in a few days

**Comment by DAN-AND-DNA** [comment]
![image](https://user-images.githubusercontent.com/28588158/227218974-4ac6402d-6fac-4605-a5cd-0a9fd1cd1415.png)
The above is the current supported platform, but I will try to change the code to be compatible with linux system

**Comment by wheresthebeefy** [comment]
Hope I'm not being a pain, but any updates on this? :)

**Comment by DAN-AND-DNA** [comment]
@wheresthebeefy Hi, it may be next Monday, but it depends on the review time

**Comment by wheresthebeefy** [comment]
Any news?

**Comment by DAN-AND-DNA** [comment]
@wheresthebeefy  Hello, I'm sorry, but we have a lot of work on our hands at the moment and no one can have time to maintain this project, so we may have to postpone the development of this new feature.
